[package]
name = "mg_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
anyhow = "1.0"
parry3d = "0.13.5"
once_cell = "1.19.0"
parking_lot = "0.12.1"

